### ISSUE TITLE
Event detail pages

### ISSUE THREAD

**Issue by weeman1337** [foss-events/website#10]
Each event should have a detail page with the following info on it:

- Event name
- Link
- Start date
- End date
- Location
  - Bonus: a map displaying the location
- Description
- Fees
- Call for papers/participation date
- Call for papers/participation link

**Comment by weeman1337** [comment]
@dreirik can you please check the list above and edit it if I missed something?

**Comment by dreirik** [comment]
@weeman1337 I would do the following set-up, using the current names of the categories in the db in "":

- "name" ("shortname")

- Homepage: "homepage"

- Date: "datestart" - "dateend" or only "datestart" for one-day events

- Type: "type"

- Location: "venue" in "city", "country" and have the "OSM-link" linked from the venue-words

- Self-description: "Self-description"

- Code of Conduct: "coclink" if there is one, else leave this field

- Entrance fee: "EntranceFee"

- Registration required? "Registration" and if it is a link it would be cool that it says "yes" and this is a link to the registration

- Number of participants last time: "ParticipantsLastTime"

- Call for Participation: "cfplink" until "cfpdate"

And then below all this information I would put then later the map showing the location and a link to follow them but only in the Fediverse.

**Comment by weeman1337** [comment]
done
