### ISSUE TITLE
redesigning global and regional days

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#100]
we have global and local days that are currently highlighted with a grey box around the name.

Proposal is to find a better design and to differentiate both from each other, so you see a difference

status quo:
![Selection_012](https://user-images.githubusercontent.com/34095056/75606425-da54e580-5aec-11ea-8a89-d219e73e75f0.jpg)

**Comment by weeman1337** [comment]
Some options that I can think of:
* Adding a ⭐
* Adding a label / badge [global] [regional]

**Comment by dreirik** [comment]
I like the idea about the star, I think it looka pretty good next to the green link colour! 
Also adding the badge seems the best idea to make differentiation easy between the two types

We could think about also "badging" the date with the similar background-grey to make it even more visible while browsing through the list.
