### ISSUE TITLE
Proposal: Using GB instead of UK in country code mapping

### ISSUE THREAD

**Issue by Calendify** [foss-events/website#107]
The country code mapping in `consts.py` is using  "UK" for "United Kingdom" instead of "GB". This does not correspond to the ISO 3166-1 alpha-2 codes. Proposal is to use "GB". This two-letter code is used in a wide range of other standards, frameworks and third-party applications.

Implementation would imply to fix also the values in CSV files.

**Comment by weeman1337** [comment]
Thanks for the report. It is fixed
