### ISSUE TITLE
introducing postponed events with new links

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#121]
cancelled events should have three values: 
a) cancelled: like now, the event shows cancelled and an individual explanation in the red top on box can be given
b) postponed without new date: like now, the event shows postponed and an individual explanation in the red top on box can be given
c) postponed with new date: like nowthe event shows postponed and an individual explanation in the red top on box can be given. in this red box will be the new link of the new dates. 
Onn the index-page the "(postponed)" of this event turns into a link to the new event. 

So we need a new field for the new link and if value is true then this should be used on the index-page

On the other end, behind the link where the new event is there should be a green box on top with individual text so we can write in that this is the postponed edition of the other event.

**Comment by weeman1337** [comment]
As discussed:

- we assign ids to the events
- we add a new field to link the replacement event
- I will figure out how to display that on the list / details page

**Comment by weeman1337** [comment]
Additional redirect. Done

As an example have a look at T-Dose
