### ISSUE TITLE
Remove redirect of postponed events

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#125]
The redirect of postponed events might not be the best choice. Not redirecting offers the chance to
- look back in time (thinking about a knowledge base)
- be useful in case the venue changes in between to consider you are looking at the correct replacement
- enable to reread individual decisions / links for postponing

**Comment by weeman1337** [comment]
Addition:
* Add a link to the replacement event to the description

**Comment by dreirik** [comment]
So let us remove the redirect? 
For example https://foss.events/2020/04-25-t-dose.html should not directly lead to https://foss.events/2020/10-24-t-dose.html but show https://foss.events/2020/04-25-t-dose.html
I will afterward ensure all links are in place

**Comment by dreirik** [comment]
since 95% of the events move online or get cancelled I see this issue with little importance meanwhile. Let us spend the energy on the other burning topics.
