### ISSUE TITLE
designing online-events-pages

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#126]
Pages that have "online" in their "cancelled" category should improve their design by:

* having the info text in green, not in red
* zoom out the osm map into a view where you see the whole world. This looks more like an Internet-event and you can still see the initial location
* write on index-page: "EVENTNAME in the Internet by {main organiser}, {country}.

Question: 
There are online-events that are a replacement for a previously planned life-event. They have (had) a "real location". Also there are online-events that happen in / for a specific location like "Vence Al Virus" for the Madrid community. And then there are global online events that have no location at all like DiVoc. Question is how we visualize the different aspects or if we do it at all.

**Comment by dreirik** [comment]
* change "only online" to "Online" in the details-page as well as on the index-page

**Comment by weeman1337** [comment]
@dreirik I think this issue is completely outdated. Maybe please write a new, clear one about new features regarding online events.

**Comment by dreirik** [comment]
@weeman1337 agree. I close this issue and open another one.
