### ISSUE TITLE
Proposal: Using AL instead of SQ in country code mapping

### ISSUE THREAD

**Issue by Calendify** [foss-events/website#132]
The country code mapping in `consts.py` is using "SQ" for "Albania" instead of "AL". This does not correspond to the ISO 3166-1 alpha-2 codes. "sq" is used instead in ISO 639-1 as a two-letter code for the language "Albanian". 

Proposal is to use "AL". This two-letter code is used in a wide range of other standards, frameworks and third-party applications for "Albania".

Implementation would imply to fix also the values in CSV files.

**Comment by weeman1337** [comment]
Thanks for the report. I think we have to distinguish between ISO 3166 for country names and ISO 639 for languages. This needs to constand lists.

**Comment by dreirik** [comment]
Agree to use 
* ISO 3166-1 alpha-2 codes for countries
* ISO 639-1 for languages

Does this need a technical implementation or is it also ok to just have this as a social rule for us to stick to these codes in the database? Should be enough, no?
After that clarification, Albania as mentioned in the example has to be updated, the rest of the list checked on its correct use.

**Comment by weeman1337** [comment]
Jep, see #156 as preparation

**Comment by weeman1337** [comment]
Done
