### ISSUE TITLE
change the URL generator to include ID instead of date

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#146]
the page generator should use the ID to create permanent URLs instead of date and name, becuase if you find a typo later and fix it the URL gets broken.

**Comment by weeman1337** [comment]
That means all URLs so far will be broken?  
We should add a redirect from the "date" to "id" URL.

**Comment by weeman1337** [comment]
For that we need a stable ID. At the moment the id could change depending on the data source.

**Comment by dreirik** [comment]
yes to the redirect from the "date to "id" URL!

I do not understand what do you mean that " the id could change depending on the data source." ? What can we do to prevent this?

**Comment by weeman1337** [comment]
> I do not understand what do you mean that " the id could change depending on the data source." ? What can we do to prevent this?
