### ISSUE TITLE
fix the date of events that pass a month

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#148]
Events with dates that pass a month (e.g. September 29 til October 1) are not shown correctly. The page should reflect both names of month, not only one, see screenshot for an exampe.
![Selection_026](https://user-images.githubusercontent.com/34095056/90976397-0651a080-e53d-11ea-8012-2f10e8589275.png)

**Comment by weeman1337** [comment]
@dreirik how should that look like in the list?

**Comment by dreirik** [comment]
sorry for not being clear enought. In the list it is fine as it is now, that's perfect: it makes the list design as simple as possible and people understand it. 

But on the individual pages it would look better imho when both months would be written out, like in the example it would be "29 September - 01 October 2020"

**Comment by weeman1337** [comment]
fixed by #230
