### ISSUE TITLE
change default map-view if no location is given

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#162]
currently the default map-view if no location is give is a place around Frankfurt. This should be changed to CERN, where the www was invented, so it has at least some meaning.

**Comment by weeman1337** [comment]
Well it points to the geographical center of the EU (before Brexit) - so it has some meaning :P

https://de.wikipedia.org/wiki/Mittelpunkt_Europas

The new one is 49.8277/9.9188

**Comment by dreirik** [comment]
ah, ok, didn't know that. Interesting! 
However, it looks like it keeps moving and is located differently depending also on the nationality of the geographer ... let's better go for CERN

**Comment by dreirik** [comment]
not needed anymore since online events now show a banner instead of the map
