### ISSUE TITLE
upate about-page

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#164]
The about-page needs another update. With the update the following should be refelected / included:
* now the side connects people via the most comprehensive list in Europe AND ONLINE. this shoudl be reflected where necessary throughout the text.
* at some point there should be an explanation about language use. This is as follows: 
  * Language of the page, categories, values etc is English
  * Descriptions can be in native language - followed by an English translation
* correct the right menu order under about:website (diversity is wrong placed)
* include a reference to the beauty of simplicity like in trivial technology or small tech etc
* update about:legend accoring to the changes we make to the data-aggregation, online and hybrid-events etc
* update criteria to include online-events and their characteristics, length (3-4h) etc

**Comment by weeman1337** [comment]
@dreirik is this issue still valid?

**Comment by dreirik** [comment]
yes, it is. I think it is time for an "about-page 2.0" that includes even more changes, some of which I already started implementing
* shorten the introduction and focus on why and how to contribute
* put contribution first (done)
* update the rest accordingly

**Comment by dreirik** [comment]
done
