### ISSUE TITLE
Introduce a visual traffic sign for variable "technical liberties" on online-event-pages

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#173]
In the detail-pages of online-events, see #151, 
we can introduce a traffic sign for the variable "technological liberties" that informs users iconicly about the technological liberties in use:

	green: users can access all content and fully participate in an online event by using foss software only and the backend is using foss software only as well
	yellow: users can access all content and fully participate in an online event but at least parts of the backend, and services in use by the organisers are set-up with proprietary software
	red: user must use proprietary software to fully connect or participate

Software examples and what colour they end up:
	Green: Rocket Chat, IRC, Discourse, Jitsi, Big Blue Button, Peertube, Mumble, Mozilla Hubs
	Yellow: Telegram, Youtube
	Red: Discord, Twitch, Slack

**Comment by weeman1337** [comment]
Okay now I get the "technological liberties" .

I still think it is not intuitive. I have to think about that one..

btw. Youtube is 100 % proprietary ;)

**Comment by dreirik** [comment]
yeah, youtube is 100 proprietary but at least you do not have to install proprietary software on your devices but can look it via a free software browser.

and yes, I also think there should be a link to the legend somewhere so people can look it up if they are interested, good point!

**Comment by weeman1337** [comment]
> yeah, youtube is 100 proprietary but at least you do not have to install proprietary software on your devices but can look it via a free software browser.

Following this logic Discord, Twitch and Slack should be Yellow as well.

> and yes, I also think there should be a link to the legend somewhere so people can look it up if they are interested, good point!

Other ideas:
- Name it something like _Event tech foss based_
- Why not writing it into the field? Maybe coloured (green, yellow, red) as it is something like a traffic light?
  - _Foss only_ : _users... bla_
  - _Partially foss_: _users... parts of the backend... bla_
  - _Proprietary_: _description here..._

That does not mean put it into the "db" field. Instead it could be done in the template process.
