### ISSUE TITLE
iCal feed for all events

### ISSUE THREAD

**Issue by jarofgreen** [foss-events/website#196]
I see you have an ical feed for individual events; is there one for all events? 

This would make the data you have easier to take and reuse.

Sorry if I missed it, but I couldn't see one on the home page.

Are you interested in having one? I might try a pull request if so.

**Comment by weeman1337** [comment]
Hi @jarofgreen we have already started working on this. But it is not ready yet.

You can find some code here: https://github.com/foss-events/website/blob/master/generator/ical_files.py#L58

I think we have to switch to a database system approach instead of the CSV "database" since version numbers for the ical events are required.

**Comment by jarofgreen** [comment]
> I think we have to switch to a database system approach instead of the CSV "database" since version numbers for the ical events are required.

Interesting. Can you use the latest git log timestamp as a version int? 

This is getting into a different topic but I had also wondered about storing one event per file instead of a CSV for other reasons, but that would help with this too. I would be very interested in chatting about a general approach here if you are up for that, as I've worked on several such systems in the past (database and data in git ones) and have open source/open data event listings code available. My motivation is basically making sure whatever you do has a lot of Open Data available :-)

**Comment by rugk** [comment]
Just discovered this and yeah I agree such a feature would greatly improve the value of the service.

As for version numbers yeah maybe JSON would be a better format anyway? (And with ChatGPT you can likely write a converter in a very easy way.)

Then either embed a manual version number or split it into multiple files and use the change date or as already suggested git commit hash.
Or well actually a hash over the content works also be possible if it is just to detect "when file has changes". Such a way could be transparent and automatic.
