### ISSUE TITLE
update tagline format for each event on front-page in list view

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#203]
proposal to update the tagline format for each event on front-page in list view, for online events and offline to events to show the following information:
[NAME] in [Location] by [Organisation]

**Comment by dreirik** [comment]
Updating this to with the ideas from #151 but still keeping it simple I propose:

Offline events: [Name] in [City], [Country] by [Organisation]
Online events: [Name] on the Internet by [Organisation]

**Comment by weeman1337** [comment]
depends on #163

**Comment by dreirik** [comment]
This has been merely done but there should be a small correction to the current version and always put organiser first: 

Online events: [Name] by [Organisation]
Offline events: [Name] by [Organisation] in [City], [Country] 
Hybrid: [Name] +„online badge“ by [Organisation] in [City], [Country]

**Comment by weeman1337** [comment]
> Online events: [Name] by [Organisation]

Should be `Online events: [Name] + „online badge“ by [Organisation]` ?

**Comment by dreirik** [comment]
done
