### ISSUE TITLE
incorrect date format in dates that span over a month 

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#204]
When the event date starts in one month but ends in the next one, the date on the individual page does not reflect that but shows only the name of the first month for both days. For example: https://foss.events/2021/06-28-thx-2021.html

The event starts on June 28 and ends in July 11 and the date says: "28-11 June 2021" instead of "28 June - 11 July 2021"

**Comment by afif1400** [comment]
can I work on this?

**Comment by dreirik** [comment]
Hi Afif! Thank you very much for getting in contact, feel very welcome and sorry for the late reply. 
It would be great if you could work on that!
