### ISSUE TITLE
Update preview image to show the individuals event name

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#205]
Currently, a post in a forum with a link to an individual event shows 

"// foss.events

The most comprehensive collection of FOSS events in Europe and online"

This preview should better reflect also the individuals event name: 

"Everything in a nutshell about [NAME] at // foss.events - 
The most comprehensive collection of FOSS events in Europe (and online)"

**Comment by weeman1337** [comment]
Isn't that something for our meta data guru @mxmehl ? :D

**Comment by dreirik** [comment]
thank you @mxmehl for the hint and the pre-work, now works and updated!
