### ISSUE TITLE
Compact index page

### ISSUE THREAD

**Issue by weeman1337** [foss-events/website#228]
To bring focus on the „main content“ (= event list) we should save some space.

Some first thoughts

![image](https://user-images.githubusercontent.com/6216686/146646467-0f20b1d2-b612-44f1-bae3-fae510017259.png)

**Comment by dreirik** [comment]
good idea. I think it could also make sense to turn around name and menu, so the menu is on top. This way it doe not distract from the actual content and title and subheading merge better into one, for example:
![foss-events-frontpage-pic](https://user-images.githubusercontent.com/34095056/147661080-bcaf688e-676a-49a5-a7a0-78b89868b5bb.jpg)

**Comment by dreirik** [comment]
on the other hand I thought about putting the news / mastodon-feed more on top since this is our "news" section and most interesting for regular visitors and naturally on top of a page ... here is an example, although not yet quite happy with it:
![foss-events-frontpage-withnews](https://user-images.githubusercontent.com/34095056/147661837-4e43a004-4a4e-4988-8fd5-7eb56c82f5f5.jpg)

**Comment by weeman1337** [comment]
> most interesting for regular visitors and naturally on top of a page

I guess the most interesting things are the upcoming events.

**Comment by smierz** [comment]
imo the social buttons should be moved into a footer like https://media.nngroup.com/media/editor/2019/01/16/clarity.png
the footer should also hold and replace the menu on the about page 
![grafik](https://user-images.githubusercontent.com/7470468/147747743-123f9364-a54a-4bad-8149-32a4a6518ff5.png)

+ the about page is quite long and should be split into several pages, e.g. about, contribute, metadata schema (=about legend), license, contact where each page fits onto a normal laptop without scrolling (which would make the footer visible at all times)

**Comment by dreirik** [comment]
I think moving social media buttons and the menu on the about page into the footer is an excellent idea @smierz !

This way the header on the front-page can be very small and simple. In addition I propose to put only two links on the top which would be a button for "community" that links to the Matrix chat room and a button "contribute" that links to the conribute section. I made an ugly proposal here to show what I mean:
![newindex](https://user-images.githubusercontent.com/34095056/148660913-d6cc1645-6a97-4143-a9a5-435686207d72.jpg)

Regarding the split of the about page into several pages I am not sure if this is of help. I mean now it has the benefit that you have all in one page, you only need to scroll and no clicking around. Also the question what is "a normal laptop" and how many access foss.events via mobile and so, you might not be able to achieve that the footer is visible all times.

**Comment by dreirik** [comment]
I removed the subheadline and added - temporarily - the matrix room, see #240
![Selection_004](https://user-images.githubusercontent.com/34095056/148837365-89e606c7-0ad0-4b2c-8c22-80734fb9a489.png)

**Comment by dreirik** [comment]
btw, I just had a look at our Umami instance and since its recording (40 days or so) only 8% of our visitors clicked on one of the menu icons in the head so we can indeed safely move it to the footer. I will give this a try with my next PR

**Comment by weeman1337** [comment]
Uff - I think it is possible to compact the header without moving stuff around. 8 % is a great conversion rate btw. ;)
