### ISSUE TITLE
locating the contribute-banner

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#23]
currently, the banner with "missing an event? etc ..." shows at the end of the section "upcoming". It would be nice if it would always show up after the second or the third month in the row, so people see it earlier not only if they scroll down to the end.

**Comment by weeman1337** [comment]
Should we display it twice or only after the second/third month?

**Comment by weeman1337** [comment]
We will show the banner after March

**Comment by weeman1337** [comment]
Done
