### ISSUE TITLE
Remove ? on the index pages

### ISSUE THREAD

**Issue by weeman1337** [foss-events/website#239]
There are currently some question marks on the index pages:

![image](https://user-images.githubusercontent.com/6216686/147751097-419fe26d-a1a1-4e73-8903-e99ac08a7268.png)

- language
- organiser

If there is a `?` provided we should just not display it at all.

**Comment by dreirik** [comment]
agree to better not display it at all

**Comment by weeman1337** [comment]
solved by ec0593eea5448ff918859c8f266040cf8783c191
