### ISSUE TITLE
improve social media preview

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#25]
currently the preview of social media lacks the logo. 
also the "in Europe is double":

![Selection_037](https://user-images.githubusercontent.com/34095056/70175574-4505a900-16d7-11ea-84ff-f34ad6e71040.png)

It should only say:
// foss.events
A collection of FOSS events in Europe

**Comment by mxmehl** [comment]
See the new pull request. It needs some help and review though :)

**Comment by weeman1337** [comment]
I've reopened this. @dreirik please feel free to close after review/test or add any feedback here.

**Comment by dreirik** [comment]
Before the information was double, now it has been removed both and only says "// foss.events": 

![Selection_047](https://user-images.githubusercontent.com/34095056/71697531-8e214980-2db8-11ea-90cf-f72c0955cdff.png)

It should better read: 
"// foss.events
A collection of FOSS events in Europe"

thank you!

**Comment by weeman1337** [comment]
@mxmehl your business ;)

**Comment by mxmehl** [comment]
Not sure why this happens. The Twitter card validator and the [open graph check](https://opengraphcheck.com/result.php?url=https%3A%2F%2Ffoss.events) tell me that everything is rather fine.

**Comment by dreirik** [comment]
Since I had the same issue again, I checked it by looking at https://mastodon.social/@FOSS_events and saw it looks fine there as defined in the open graph check. So it seems maybe a problem of my rambox client. Can someone verfify this / check with his client?

**Comment by weeman1337** [comment]
ping @mxmehl

**Comment by weeman1337** [comment]
maybe layer 8 problem :trollface: → closed
