### ISSUE TITLE
changing name on github from flossevents to fossevents?

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#26]
Can we change the name on github from flossevents to fossevents, please?

**Comment by weeman1337** [comment]
Unfortunately we can't. The username "fossevents" has already been taken: https://github.com/fossevents/

We could try something with "." or "_" in the name?

**Comment by weeman1337** [comment]
Here are the GH rules: "Username may only contain alphanumeric characters or single hyphens, and cannot begin or end with a hyphen "

**Comment by dreirik** [comment]
well, there is no other choice instead of including numbers which does not fit pretty good, so yes, let's go with foss-events : )

**Comment by weeman1337** [comment]
Renamed to foss-events
