### ISSUE TITLE
`add to your calendar` link returns 404

### ISSUE THREAD

**Issue by aalemayhu** [foss-events/website#271]
I was expecting a link to valid ICS file but instead see the below

<img width="464" alt="Screenshot 2022-12-04 at 3 20 01 PM" src="https://user-images.githubusercontent.com/925044/205495858-e3e8e670-1272-4f33-86cb-4791a8fb5e21.png">

## Steps to reproduce

1. Visit https://foss.events/2023/02-03-chaosscon-europe.html
2. Click [add to your calendar](https://foss.events/2023/02-03-chaosscon-europe.ics)

**Comment by doczkal** [comment]
Thanks for posting. I was about to open an issue with similar content.
The ICS-file is missing for all events with a sub page.
