### ISSUE TITLE
Open Source Summit 2023 month wrong

### ISSUE THREAD

**Issue by mxmehl** [foss-events/website#291]
According to the official [website](https://events.linuxfoundation.org/open-source-summit-europe/), the event takes place from 19-21 September, not October.

https://github.com/foss-events/website/blob/a5f88ca17395847744a3c60e3e69b9e57004b50e/data/2023_events_db.csv#L77

**Comment by dreirik** [comment]
Hi Max, thank you for noticing and letting us know, we have corrected our data
