### ISSUE TITLE
Flexibel content for the cfps

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#30]
Sometimes events have a very easy cfp-process that basically asks to send in an email with a proposal. For example: https://wiki.f-si.org/index.php/FSiC2020

Also they then often do not have a specific page dedicated to the cfp but use the very same page for the event as for the cfp. Taking the example above, it could make sense in this case to directly show: "Everybody is welcome to propose a talk by writing to fsic2020 'at' f-si.org. The submission window will open on January 1 2020 and will close on March 31 2020. Acceptance will be communicated by April 10."

**Comment by weeman1337** [comment]
Okay understand the case. But how should we do it then? Do we have two fields? One for a link to the CfP and one with text content?

**Comment by weeman1337** [comment]
@dreirik  is this similar to  #47?

**Comment by weeman1337** [comment]
done
