### ISSUE TITLE
cosmetic facelifting events-pages

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#31]
Proposals for a cosmetic facelift of the individual event pages already visible on test.foss.events:

- [x] Have the complete headline "FOSS events in Europe" as a link to the homepage. Then leave out the years (2019 | 2020) on these pages.
- [x] Below the title of the event where is written the "type" variable, there should be printed "Type: {type}". I think it should also be with bigger latter, it is hard to realise there is written something at all.
- [x] Either we should put the date and location in bold or also print "Date:" and "Location:" on the left side. Currently I think it is difficult to get it, although this is maybe for most visitors the most important information. 
- [x] Registration: I would change this into "Registration required?" and then have "Yes", "Yes" with a link and "No". Or leave it has it is now but then include a "No registration required" for those who have a "no" in the db
- [x] change "description" into ~~"Self-description"~~ *Their self-description* because that is what it is : )
- [x] change "Entrance fee" into "Participation fee" or even better "Standard participation fee" if place allows
- [x] change "CoC" into "Code of Conduct" and as the text put only "Link" with the link. I think barely anyone understands CoC
- [x] change "Event size" into "Participants last time" and as a value we put only the number itself and we can begin that number with a "~". Where we have no number there should be a "?", the question is if we put a "?" in the db or if this is better done automatically when there is no data?
- [x] the banner in the end should say "missing info? info out of date? please contribute"

That's for the moment. Thanks for fixing!

**Comment by weeman1337** [comment]
> change "description" into "Self-description" because that is what it is : )

Never heard of that one..

> Either we should put the date and location in bold or also print "Date:" and "Location:" on the left side. Currently I think it is difficult to get it, although this is maybe for most visitors the most important information.

I'm also not happy with that. I'll try to improve it.

> change "Event size" into "Participants last time" and as a value we put only the number itself and we can begin that number with a "~". Where we have no number there should be a "?", the question is if we put a "?" in the db or if this is better done automatically when there is no data?

If we don't know it - why not just skip that field? If we display it, I would just write the content of the CSV and there can be anything (text).

**Comment by dreirik** [comment]
> > change "description" into "Self-description" because that is what it is : )
> 
> Never heard of that one..

The point is that what we do is we copy-paste the description that is available on the webpage without any evaluation from our side. That is why I would like to see "self-description" as is written in the db.

> > Either we should put the date and location in bold or also print "Date:" and "Location:" on the left side. Currently I think it is difficult to get it, although this is maybe for most visitors the most important information.
> 
> I'm also not happy with that. I'll try to improve it.

ok, cool : )

> > change "Event size" into "Participants last time" and as a value we put only the number itself and we can begin that number with a "~". Where we have no number there should be a "?", the question is if we put a "?" in the db or if this is better done automatically when there is no data?
> 
> If we don't know it - why not just skip that field? If we display it, I would just write the content of the CSV and there can be anything (text).

The point is if we put "?" then my hope is that if someone knows it (s)he might improve it and give us a hint : )
But yes, then let's simply put what is written in the db (text) and I put "?" there : )

thank you

**Comment by weeman1337** [comment]
@dreirik all done https://test.foss.events/

Please reload with bypassing cache

**Comment by weeman1337** [comment]
No feedback here but all done → closing
