### ISSUE TITLE
Add to calendar

### ISSUE THREAD

**Issue by weeman1337** [foss-events/website#36]
An user should be able to add events to his calendar.

For this we want to add buttons "add to my calendar" on the event detail page. There should be two buttons next to the event date and the call for participation deadline.

An item should contain:

- Event label
- Event date
- Location: Readable location
- URL to the foss events details page
- Geo coordinates
- Description including OSM Link, foss events details page link and official homepage link

The CfP calendar links will be done in a separate issue.

**Comment by dreirik** [comment]
The set-up looks pretty good to me, thanks! 
There are some design-issues when I just tested it, see this screenshot:

![Edit Event: Opensouthcode_051](https://user-images.githubusercontent.com/34095056/71766604-f0d22c80-2f01-11ea-9081-0330768372b1.png)

- the paragraph-tags should not be visible but in the best case should be interpreted

- a blank line between each point would be nice. Meaning a blank line between the description and "more info", between "more info" and "official homepage", between "offical homepage" and "find your way"

- The date says it starts 24.4. and ends 24.4, although the db says it ends 25.4.

**Comment by weeman1337** [comment]
> the paragraph-tags should not be visible but in the best case should be interpreted

The paragraphs are in the CSV source code, right? It's ugly to parse that out but I'll try. We are now mixing up different "markdown" styles.

**Comment by weeman1337** [comment]
@dreirik please have another look

- `</p>` HTML tags are replaced by two line breaks
- `<br>` is replaced by one line break

All other HTML tags are stripped out.

**Comment by dreirik** [comment]
looks pretty good for me now:

![Edit Event: Opensouthcode_052](https://user-images.githubusercontent.com/34095056/71768842-88dc1000-2f1a-11ea-9452-6dea8bd3a742.png)

well done!

**Comment by dreirik** [comment]
still looking for a button to display here? @weeman1337

**Comment by weeman1337** [comment]
Waiting for a review by Max, see #46
