### ISSUE TITLE
keep notice about cfp's on event-suppages after the deadline has passed

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#41]
In the event's subpage templates now we see for example "Call for Participation: Take part. Deadline: 06.01.2020" until the deadline has passed and afterwards nothing anymore. It would be nice to see afterwards "Call for Participation: What a pity! The deadline for this CfP passed on 06.01.2020."

On the front-page with the overview list it should not be visible after the deadline as it is now.

**Comment by weeman1337** [comment]
Should we display the deadline for passed events as well?

**Comment by dreirik** [comment]
? 

as written above: not on the front-page. But on the subpages I would put something like "The deadline for this CfP passed on DD.MM.YYYY"

**Comment by weeman1337** [comment]
done
