### ISSUE TITLE
redesigning the header, include social media outreach

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#42]
Hi all, 

we possibly like to have more outreach by highlighting more our social media, github and contact-possibilities. Therefore I created a design-proposal for the header, see screenshot here:

![social-design2](https://user-images.githubusercontent.com/34095056/71766754-9fc33800-2f03-11ea-9ebd-6ea57ec0c8ad.jpg)

This is just a quick graphic. Of course, size and arrangement of the web-icons can and should be improved. The proposal is more about the general concept. 

The good thing is we can repeat the header and the web-icons on every subpage as well. As long as we do not have a menu anyway, this would be a good solution to boost our outreach.

btw: the web-icons are: mastodon, twitter, github, about-page, emailcontact

Links:
* https://mastodon.social/@FOSS_events
* https://twitter.com/FOSS_events
* https://github.com/foss-events/website
* about page
* email enquiry

**Comment by dreirik** [comment]
and here a second version: 

![social-design](https://user-images.githubusercontent.com/34095056/71766796-414a8980-2f04-11ea-9d49-8a61e91835be.jpg)

let me know what design you prefer.

**Comment by weeman1337** [comment]
I like the second one. Looks less like a Todesanzeige ;)

Where will we put the year links then?

**Comment by dreirik** [comment]
haha

ah, sorry, forgot that. I think 2019 is not very interesting anymore. Especially as all the sub-pages have basically no additional information. So I propose to put at the end of the 2020 list a new headline saying "Archive" and there "List of FOSS Events in Europe in 2019" and link from there to the 2019 page.

**Comment by dreirik** [comment]
I now uploaded same-style-looking buttons for a start to be used in the header. the actual grey color can still be subject of discussion, but I had the feeling grey is better than the green to not overload attention on the header. 

You find the buttons in /src/img/ see this PR: https://github.com/foss-events/website/pull/51

**Comment by weeman1337** [comment]
This somehow collides with Max's Social Media buttons. How do we want to integrate these? Or will we have both: These links to the pages and additionally a "share" function?

**Comment by dreirik** [comment]
As said in issue #53 I would leave the share buttons off the home page. In the sub-pages I do not see them collide. One is on top, other on the bottom. One is our accounts to follow, others are share buttons for users to use.

**Comment by weeman1337** [comment]
That is want I meant and what my question was

**Comment by dreirik** [comment]
I have some other design suggestion for the header, this time with the wordmark instead of a title:

![header-with-green-webs](https://user-images.githubusercontent.com/34095056/72228696-5df05c80-35a9-11ea-8ba7-487d39de4bb5.png)


![header-with-grey-webs](https://user-images.githubusercontent.com/34095056/72228700-6183e380-35a9-11ea-8c97-40af67971566.png)

![header-with-less-green-webs-without logo](https://user-images.githubusercontent.com/34095056/72228704-66e12e00-35a9-11ea-812f-a7dc9565fa6e.jpg)

**Comment by weeman1337** [comment]
I'm for the last one

**Comment by weeman1337** [comment]
done
