### ISSUE TITLE
have a list of upcoming cfp-deadlines only

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#43]
I think it would be nice to have somewhere on the page a list of deadlines that will pass soon, in best case listed in chronological order. No idea yet, where exactly on the page to put this list. But I think this would be an interesting list for a certain group and I wanted to put down the idea before I forget it.

**Comment by weeman1337** [comment]
>  No idea yet, where exactly on the page to put this list.

Why not create a special page for that?

**Comment by dreirik** [comment]
yes, I think that makes more sense, thank you for the suggestion!

I wonder however, where to put it, though ...

Maybe with a 1-time box after a third of the list similar to the style "missing an event? [...]" saying something like "Are you a regular speaker, presenter, facilitator or any other contributor to FOSS events? Check out our dedicated list of upcoming call for participations". 

what do you think?

**Comment by weeman1337** [comment]
In my opinion we should think about some kind of menu structure. There should be a link for that. Then it is easily to find.

**Comment by liquidat** [comment]
There is basically a menu structure on top: the five icons for mastodon, Twitter, the page itself, github and the bout page. How about we add something right to the calendar icon itself. It would lead to a page designed like the current one but with a different headline.

What I am not sure about is: do we already track those information? The mail template asks for
```
Link for Call for Participation:
Deadline for Call for Participation:
```

Honestly I have no idea if this means the CfP dates or something else.
