### ISSUE TITLE
include "?" as a possible value in registration-variable

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#47]
to further enhance contributions and crowdsourcing information collection we should use more "?" in those variables that we have no idea of instead of leaving the field blank. 

if, for example, we have no idea if registration is required it would be good to have the option to include "?" as a value. I tried it now for BalCCon but then it is getting interpreted as a link. 

best fix for this and other similar types (e.g. link for CoC etc) would be to check if it it an URL -> print "yes" with the link. Else: print freetext.

**Comment by weeman1337** [comment]
For the registration it now works like this:
* empty field → ?
* URL (starting with http) → yes as link
* else just the field value

For *similar types* maybe just open another thing with a list that can be checked so I know what to do. E.g.

* [ ] type A
* [ ] type B
