### ISSUE TITLE
designing the share buttons

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#53]
Since the PR of the share buttons is already closed https://github.com/foss-events/website/pull/39, I open an issue to further discuss the design 

A) I would leave out the share buttons on the homepage. They confuse me a bit and they will more once we integrate the new header, see https://github.com/foss-events/website/issues/42 

Also, while I think it makes sense for the subpages to have share-buttons I doubt it makes sense for the general home-page. So I vote for only integrating it on the sub-pages.

B) Maybe it makes sense to use only one color for the social media buttons. On one hand the many colours contradict a little bit our clean design. On the other hand some colors are nicer than others or extraordinary (reddit now, e.g.) and it gives somehow a ranking by using different colors. It would be better imho to use different scales of the same color or of different greys. 

C) It should have a headline like : "Share this event in your channels:"

D) Who wrote the email-description "Read more on // foss.events - the most comprehensive list of FOSS events in Europe"? I love it : )

**Comment by mxmehl** [comment]
I don't have a strong opinion here. The current setting is that on the front page, they are shown in the left sidebar, scrolling with the screen, so not colliding. But indeed, it's a bit duplicated.

Regarding the colors, I think they are necessary for visitors to identify. But sure, we can change them...

> C) It should have a headline like : "Share this event in your channels:"

I could only tackle this next week, but sure, that's easy.

> D) Who wrote the email-description "Read more on // foss.events - the most comprehensive list of FOSS events in Europe"? I love it : )

Could have been me, not sure any more :D
