### ISSUE TITLE
fix the foss-event-link in the calendar-export

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#60]
when I import an event from foss.events now, it shows me for example: 

"More info at // foss.events: 2020/04-25-open-education-day.html"

This should be 

"More info at // foss.events: https://foss.events/2020/04-25-open-education-day.html"

so I can easily copy-paste the link and look at it. Also some clients might natively interpret it as a clickable link by default.

As text I propose:

"Read everything about {name} in a nutshell on // foss.events: full-URL"

**Comment by weeman1337** [comment]
✓ done
