### ISSUE TITLE
have the default link without underline

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#66]
In favor of removing "underline" globally for all links. Any opinions on that? If you think the same, just do it without re-asking.

**Comment by weeman1337** [comment]
At the moment we have to types of link styles:
• without underline like the event pages
• with underline like the links you mentioned

In my opinion one should be enough. I vote for marking links by green text color without underline. When hovering with the mouse links could have an underline.

**Comment by weeman1337** [comment]
Done, also added a starting point for the styleguide: https://github.com/foss-events/website/blob/master/doc/styleguide.md
