### ISSUE TITLE
Backup of logs and stats

### ISSUE THREAD

**Issue by weeman1337** [foss-events/website#68]
Backup of the following directories once a week
* `/logs`
* `/usage`

**Comment by weeman1337** [comment]
@dreirik maybe something for you to configure on your web space.

**Comment by dreirik** [comment]
yeah, well, I have to figure out how that works : D 
maybe someone can help here during the next hack-a-thon - at least tell me how to do it so I can help myself.

**Comment by weeman1337** [comment]
@dreirik is this still valid?

**Comment by dreirik** [comment]
this is out of priority for now
