### ISSUE TITLE
Event disappears on end day

### ISSUE THREAD

**Issue by weeman1337** [foss-events/website#70]
For example the ILFS day disappears on 14th Feb.. The end date is the 14th, too.

Expected: The event should be displayed the entire 14th.

**Comment by weeman1337** [comment]
I'm no longer sure about that. @dreirik that means for example *MERGE-it* ending on the 5th of April will be visible the entire 6th? Shouldn't is be removed in the nightly update on the 6th morning?

**Comment by dreirik** [comment]
yes, absolutlely. it should be visible the entire 5th and put into the past events with the nightly update on the 6th morning. Currently however, it is put into past event already on morning of the fifth. That is why we need +1 day. check it out for yourself

**Comment by weeman1337** [comment]
That is like it should work at the moment. Let's observe it this weekend.

**Comment by weeman1337** [comment]
Updated description, changed to bug

**Comment by weeman1337** [comment]
done
