### ISSUE TITLE
Display new items on the event pages

### ISSUE THREAD

**Issue by weeman1337** [foss-events/website#75]
* language
* main organizer
* edition's topic (without ? on empty
* specialties (without ? on empty)

**Comment by dreirik** [comment]
I propose to also include 'type' as a "usual" event-item, and put it on top immediately after the URL

- type

- main language

- registration required, etc.

see here as example:

![Selection_024a](https://user-images.githubusercontent.com/34095056/73890433-43409900-4872-11ea-854e-db0b325226da.png)

**Comment by weeman1337** [comment]
> put it on top immediately after the URL

Why should we put the event type into the URL?

Should it be `https://foss.events/2020/09-18-kielux-community-conference.html` ? o_O

**Comment by dreirik** [comment]
No, not in the URL. As the graphic shows, I propose to make it the second item of the list below the map with first item being the url, third item being the main language and fourth their self-description.

This would solve a bit the graphical difficulties when we have the type above the map.

**Comment by weeman1337** [comment]
done

**Comment by dreirik** [comment]
I changed order again, see #89

**Comment by weeman1337** [comment]
> I changed order again, see #89

Okay so this is still done then. Lets continue in #89
