### ISSUE TITLE
broken link-creation in the "specialties"

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#93]
we should remove the "https://foss.events/" fundament in the values of the database. Seen in the field "Specialties" for European Open Source & Free Software Law Event: 

In the db is written "Happening in conjunction with <a href=”https://foss.events/2020/04-02-merge-it.html”>MERGE-IT</a>"

and on the page: https://foss.events/2020/04-02-european-open-source-free-software-law-event.html it gets translated into "Happening in conjunction with <a href=”https://foss.events/%E2%80%9Dhttps://foss.events/2020/04-02-merge-it.html%E2%80%9D”>MERGE-IT</a>"

and the link is broken.

**Comment by weeman1337** [comment]
You are using the wrong quotes. 

” = incorrect  
" = correct

But I think I'll add replacing them to the parser.

**Comment by weeman1337** [comment]
I'll quick fix the quotes. We should go for links in the future

**Comment by weeman1337** [comment]
Done
