### ISSUE TITLE
translate country codes for "main languages" into words

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#94]
translate country codes for "main languages" into words, e.g. "EN" into "English" on the event details page

**Comment by dreirik** [comment]
might be nice to translate it in their respective languages, e.g. 
EN = English
DE = Deutsch
ES = Español
etc

**Comment by dreirik** [comment]
Optimum:
EN = "English (EN)"
DE = "Deutsch (DE)"
ES = "Español (ES)"
etc

**Comment by weeman1337** [comment]
+1, @dreirik could you prepare that by checking all values in the fields are ISO compliant? https://de.wikipedia.org/wiki/Liste_der_ISO-639-1-Codes

**Comment by weeman1337** [comment]
ping @dreirik

**Comment by dreirik** [comment]
thanks for reminding. yes, will do together with #132

**Comment by weeman1337** [comment]
See also  #156 as a preparation.
