### ISSUE TITLE
Include a link to the original source in "their self-description"

### ISSUE THREAD

**Issue by dreirik** [foss-events/website#97]
Let's make it obvious that this the self-desciption is copypasted from the webseite

One solution would be as the title says to have written
(copy&pasted)
on the left side, below "Their self-description", after a line break.

**Comment by weeman1337** [comment]
@dreirik what about a simple solution like adding a sentence "source: https://blubb" if you're copying it at the end of the text?

**Comment by weeman1337** [comment]
Example 
![image](https://user-images.githubusercontent.com/6216686/78499778-f0407080-7752-11ea-8675-f9b59a36b220.png)

As you see it doesn't matter which description field. Just adding a link may be the simplest solution

**Comment by weeman1337** [comment]
ping @dreirik

**Comment by dreirik** [comment]
yes, that's smarter : ) 

so let's put the description from now on in "quotes" and add a link to the source in the end. 
In case it is a non-English language it should be followed by an English translation like stated in #164 though it sound like a lot of work. But using a translator it should be do-able-ish : D

**Comment by weeman1337** [comment]
@dreirik I think this issue wasn't about translations ;)

The topic is "link to the source". You asked about a dedicated field for that. I suggested just putting it into the description text.

**Comment by weeman1337** [comment]
Done
